modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ironblood"
version="0.0.1"
displayName="IRONBLOOD"
displayURL="https://github.com/greathive/ironblood"
credits="greathive"
authors="Greathive"
description="A Valkyrien-Skies addon adding mecha content and capabilities."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ironblood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ironblood]]
    modId="valkyrienskies"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration