modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ironblood"
version="1.0.0"
displayName="IRONBLOOD"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="User, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ironblood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ironblood]]
    modId="valkyrienskies"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration